import type { DrawingObject } from "./drawing-types";
import { SABAHLOT_OFFICIAL_DISCLAIMER } from "./legal-disclaimer";

export interface ExportPoint {
  id: string;
  pointCode: string;
  pointName: string;
  category: string;
  coordinate: { lat: number; lng: number };
  isVisible: boolean;
}

export const DXF_CRS_NOTICE =
  "DXF Alpha output uses WGS84 longitude/latitude coordinates. Metric projected coordinate export will be handled in a later CRS enhancement phase.";

const PRELIMINARY_NOTICE = SABAHLOT_OFFICIAL_DISCLAIMER;

const xmlEscape = (value: string) =>
  value.replace(/[&<>"']/g, (character) =>
    ({
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&apos;",
    })[character] ?? character,
  );

const categoryLabel = (value: string) =>
  value
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

const coordinateText = (
  coordinates: Array<{ lat: number; lng: number }>,
) =>
  coordinates
    .map((coordinate) => `${coordinate.lng},${coordinate.lat},0`)
    .join(" ");

const closeRing = <T extends { lat: number; lng: number }>(coordinates: T[]) => {
  const first = coordinates[0];
  const last = coordinates.at(-1);

  return first && last && (first.lat !== last.lat || first.lng !== last.lng)
    ? [...coordinates, first]
    : coordinates;
};

const description = (rows: Array<[string, string]>) =>
  `<description><![CDATA[${rows
    .map(
      ([label, value]) =>
        `<strong>${xmlEscape(label)}</strong>: ${xmlEscape(value)}`,
    )
    .join("<br/>")}]]></description>`;

export function buildKmlDocument(
  lotName: string,
  drawingObjects: DrawingObject[],
  points: ExportPoint[],
) {
  const placemarks = [
    ...points.filter((point) => point.isVisible).map(
      (point) =>
        `<Placemark><name>${xmlEscape(
          point.pointName.trim() || point.pointCode,
        )}</name><styleUrl>#sabahlot-point-style</styleUrl>${description([
          ["ID", point.id],
          ["Object Type", "Point"],
          ["Category", categoryLabel(point.category)],
          ["Status", "Preliminary"],
          ["Disclaimer", PRELIMINARY_NOTICE],
          ["Generated By", "SabahLot powered by Myukur"],
        ])}<Point><coordinates>${coordinateText([
          point.coordinate,
        ])}</coordinates></Point></Placemark>`,
    ),
    ...drawingObjects.filter((object) => object.isVisible).map((object) => {
      if (object.geometryType === "polygon") {
        return `<Placemark><name>${xmlEscape(
          object.name,
        )}</name><styleUrl>#sabahlot-boundary-style</styleUrl>${description([
          ["ID", object.id],
          ["Object Type", "Approximate Polygon Boundary"],
          ["Category", categoryLabel(object.category)],
          ["Status", "Preliminary"],
          ["Estimated Area", `${object.areaSqm.toFixed(2)} m2`],
          ["Disclaimer", PRELIMINARY_NOTICE],
          ["Generated By", "SabahLot powered by Myukur"],
        ])}<LineString><tessellate>1</tessellate><coordinates>${coordinateText(
          closeRing(object.coordinates),
        )}</coordinates></LineString></Placemark>`;
      }

      const lineKind = object.lineStyle === "solid" ? "Solid Line" : "Dashed Line";
      return `<Placemark><name>${xmlEscape(
        object.name,
      )}</name><styleUrl>#sabahlot-line-style</styleUrl>${description([
        ["ID", object.id],
        ["Object Type", lineKind],
        ["Category", categoryLabel(object.category)],
        ["Status", "Preliminary"],
        ["Length", `${object.lengthM.toFixed(2)} m`],
        ["Disclaimer", PRELIMINARY_NOTICE],
        ["Generated By", "SabahLot powered by Myukur"],
      ])}<LineString><tessellate>1</tessellate><coordinates>${coordinateText(
        object.coordinates,
      )}</coordinates></LineString></Placemark>`;
    }),
  ];

  return {
    visibleCount: placemarks.length,
    content:
      `<?xml version="1.0" encoding="UTF-8"?>\n` +
      `<kml xmlns="http://www.opengis.net/kml/2.2"><Document>` +
      `<name>${xmlEscape(lotName)}</name>` +
      `<Style id="sabahlot-boundary-style"><LineStyle><color>ff00ffff</color><width>3</width></LineStyle></Style>` +
      `<Style id="sabahlot-line-style"><LineStyle><color>ff00ffff</color><width>3</width></LineStyle></Style>` +
      `<Style id="sabahlot-point-style"><IconStyle><scale>1</scale><Icon><href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href></Icon></IconStyle></Style>` +
      `${placemarks.join("")}</Document></kml>`,
  };
}

const dxfText = (value: string) => value.replace(/[\r\n]+/g, " ").trim();
const dxfPoint = (coordinate: { lat: number; lng: number }) =>
  `10\n${coordinate.lng}\n20\n${coordinate.lat}\n30\n0\n`;

function dxfPolyline(
  layer: string,
  coordinates: Array<{ lat: number; lng: number }>,
  closed: boolean,
) {
  return `0\nLWPOLYLINE\n8\n${layer}\n90\n${coordinates.length}\n70\n${
    closed ? 1 : 0
  }\n${coordinates
    .map((coordinate) => `10\n${coordinate.lng}\n20\n${coordinate.lat}\n`)
    .join("")}`;
}

const dashedLayers = new Set([
  "proposed_boundary",
  "proposed_access",
  "road_reserve",
  "setback",
  "reference_line",
]);

export function buildDxfDocument(
  drawingObjects: DrawingObject[],
  points: ExportPoint[],
) {
  const visibleObjects = drawingObjects.filter((object) => object.isVisible);
  const visiblePoints = points.filter((point) => point.isVisible);
  const layers = [
    "LOT_BOUNDARY",
    "LINE",
    "DASHED_LINE",
    "PROPOSED_BOUNDARY",
    "PROPOSED_ACCESS",
    "ROAD_RESERVE",
    "SETBACK",
    "REFERENCE_LINE",
    "POINT",
    "TEXT_LABEL",
  ];
  const layerTable =
    `0\nTABLE\n2\nLAYER\n70\n${layers.length}\n` +
    layers
      .map(
        (layer, index) =>
          `0\nLAYER\n2\n${layer}\n70\n0\n62\n${index === 1 ? 3 : index === layers.length - 1 ? 7 : 1}\n6\nCONTINUOUS\n`,
      )
      .join("") +
    `0\nENDTAB\n`;
  const entities = visibleObjects
    .map((object) => {
      const layer =
        object.geometryType === "polygon"
          ? "LOT_BOUNDARY"
          : object.lineStyle === "dashed"
            ? dashedLayers.has(object.category)
              ? object.category.toUpperCase()
              : "DASHED_LINE"
            : "LINE";
      return (
        `999\n${dxfText(`${object.name} (${object.lineStyle})`)}\n` +
        dxfPolyline(layer, object.coordinates, object.geometryType === "polygon")
      );
    })
    .join("");
  const pointEntities = visiblePoints
    .map((point) => {
      const label = dxfText(point.pointName.trim() || point.pointCode);
      return (
        `0\nPOINT\n8\nPOINT\n${dxfPoint(point.coordinate)}` +
        (label
          ? `0\nTEXT\n8\nTEXT_LABEL\n10\n${point.coordinate.lng}\n20\n${point.coordinate.lat}\n30\n0\n40\n0.00002\n1\n${label}\n`
          : "")
      );
    })
    .join("");

  return {
    visibleCount: visibleObjects.length + visiblePoints.length,
    content:
      `0\nSECTION\n2\nHEADER\n999\n${PRELIMINARY_NOTICE}\n999\n${DXF_CRS_NOTICE}\n9\n$INSUNITS\n70\n0\n0\nENDSEC\n` +
      `0\nSECTION\n2\nTABLES\n${layerTable}0\nENDSEC\n` +
      `0\nSECTION\n2\nENTITIES\n${entities}${pointEntities}0\nENDSEC\n0\nEOF\n`,
  };
}
